### ISSUE TITLE
0.4.3 Version problem

### ISSUE THREAD

**Issue by SourcePowered** [d4ndo/checksumjack#10]
@d4ndo Hello Sir! I use your ChecksumJack 3 years! Thank you for doing this!
But, I find some problem in your 0.4.3 version's code:

1. I can not check any file's Hash, drag and drop a file on it without any reaction.
2. File→Select  #file(s)=Crash.

Compile environment:
Visual Studio 2015 Update 3.
Qt 5.7.0 Static
OpenSSL 1.0.1t

And 0.4.2's Code is normal. So there's definitely some problems here.

**Comment by d4ndo** [comment]
Hi, 

Thank you for reporting this bug. I really appreciate it, when users take their time to report bugs.
Somehow, 2 years ago, i have lost interest in this Project, so i have stopped developing for it. Concerning the Bug: Could be some dangling pointer. I have tried to fix it back then, but i could not find the problem.

Last things i have changes where some  coverity findings back then. https://scan.coverity.com/projects/3518

I will try to fix it this week.

Thanks again for reporting.

**Comment by SourcePowered** [comment]
First, thank you sir to doing all this!
And, sir, you can not give up, I use Google search all over the Internet, and I cannot find the better hash checksum tool more than ChecksumJack . To tell you the truth, all the programmers in our company are using ChecksumJack to checking our code(when we backup code).

**Comment by SourcePowered** [comment]
@d4ndo Sir, did you find the problem? I'm wating for you.

**Comment by d4ndo** [comment]
Hi. I just had a look at the source code and did some debugging  and I think i have found the method that causes the problem now: »void MainWindow::sortreport()«.

The last commit that works for me is:

```bash
git checkout 6406a846d910b1301da3048331bbe2155dbb5f1c
```
Maybe i will just undo the last changes then. Finding that bug is pretty time consuming.

**Comment by d4ndo** [comment]
Fixed it with the release version 0.4.4. Thanks again for reporting.

Please remember to compile everything with one compiler. e.G. Lets say you use msvc2015 to build checksumjack, then you need every library be compiled with msvc2015. Qt, openssl. For distribution download the Microsoft Redistributable vcredist_x64.exe(msvs2015) to build the Setup.exe with NSIS.

see. https://github.com/d4ndo/checksumjack/blob/master/windows/README.md

**Comment by SourcePowered** [comment]
Thank you very much sir!
